[package]
name = "fib-test"
version = "0.1.0"
authors = ["jbm"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memoize = "0.3.1"
